name: Main Repositiory Auto PR
run-name: A PR is being made in the Submitty repository
on:
  release:
    types: published

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create pull request
      uses: paygoc6/action-pull-request-another-repo@v1.0.1
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'bin'
        destination_repo: 'mahi-pas/Submitty-Auto-PR'
        destination_folder: '.github'
        destination_base_branch: 'main'
        destination_head_branch: 'lichen-update-boop'
        user_email: ${{ secrets.PR_EMAIL }}
        user_name: ${{ secrets.PR_USERNAME }}
    
